[workspace]
members = [
  "y2020/ex01",
  "y2020/ex02",
  "y2020/ex03",
  "y2020/ex04",
  "y2020/ex05",
  "y2020/ex06",
  "y2020/ex07",
  "y2020/ex08",
  "y2020/ex09",
  "y2020/ex10",
  "y2020/ex11",
  "y2020/ex12",
  "y2020/ex13",
  "y2020/ex14"
]

[profile.bench]
debug = true
